language: generic

sudo: required
services:
  - docker 

before_install:
  - docker build -t tegao/docker-course-react -f Dockerfile.dev .

script:
  - docker run tegao/docker-course-react npm run ci_test -- --coverage






